#!/usr/bin/env python3
"""Generate the committed RIR fixtures in tests/fixtures/.

Room impulse responses used as feedback paths F in the closed-loop
regression tests. Two sources of truth:

  --generate     Rebuild the physically-modeled rooms defined in ROOMS
                 below (pyroomacoustics image-source method: deterministic,
                 reproducible bit-for-bit from these parameters). These are
                 the shipped fixtures until measured rooms replace or join
                 them.

  --from-wav WAV NAME --source "..."
                 Convert a measured RIR (an academic dataset room, or your
                 own swept-sine measurement) into a fixture header. State
                 the provenance and license in --source; it is embedded in
                 the header, because the fixture becomes a permanent
                 pass/fail baseline and future readers must know what room
                 they are being judged against. The WAV must be mono; if
                 its rate is not 48 kHz it is resampled (needs scipy).

Every fixture is processed the same way, documented here once:
  1. trim the bulk propagation delay to a 32-sample guard before the
     first sample within 40 dB of the peak (the tests' canceller lengths
     then model the room, not silence);
  2. truncate to TAPS samples (85 ms at 48 kHz: the direct sound, the
     early reflections and the early tail — what a practical canceller
     filter length covers);
  3. normalize to unit energy (matching the synthetic fixtures, so gain
     numbers stay comparable across rooms).

Requires: numpy; pyroomacoustics for --generate; scipy only if a WAV
needs resampling.
"""

import argparse
import pathlib

import numpy as np

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT_DIR = REPO_ROOT / "tests" / "fixtures"
FS = 48000
TAPS = 4096
GUARD = 32  # samples of true pre-delay kept ahead of the direct sound

# The modeled rooms. Deliberately differentiated: a dry nearfield studio,
# a mid-size rehearsal room, and a reverberant hall with a distant mic —
# the axis along which feedback cancellation gets harder.
ROOMS = {
    "studio": dict(
        dims=[5.0, 4.0, 2.8],
        absorption=0.35,
        max_order=17,
        speaker=[1.0, 2.0, 1.2],
        mic=[2.1, 2.4, 1.3],
        blurb="small dry control room, mic 1.2 m from a wedge",
    ),
    "rehearsal": dict(
        dims=[8.0, 6.0, 3.5],
        absorption=0.20,
        max_order=17,
        speaker=[2.5, 3.1, 1.7],
        mic=[5.5, 2.0, 1.4],
        blurb="mid-size rehearsal room, mic 3.2 m from the speaker",
    ),
    "hall": dict(
        dims=[15.0, 10.0, 6.0],
        absorption=0.12,
        max_order=17,
        speaker=[4.0, 5.0, 2.0],
        mic=[9.5, 4.2, 1.6],
        blurb="reverberant hall, mic 5.6 m out — the PA scenario",
    ),
    # The automotive scenario for the ITU compliance suite (Stage 1):
    # ~2.6 m^3 enclosure, heavy absorption, RT ~60 ms — the car-interior
    # figures G.167 5.2.3.1 specifies for mobile echo paths. Speaker in
    # the footwell, mic at the mirror position.
    "cabin": dict(
        dims=[1.9, 1.45, 0.95],
        absorption=0.75,
        max_order=40,
        speaker=[0.35, 0.4, 0.25],
        mic=[1.1, 0.7, 0.85],
        blurb="car cabin, mic at the mirror, speaker in the footwell",
    ),
}


def condition(rir: np.ndarray) -> np.ndarray:
    rir = np.asarray(rir, dtype=np.float64)
    peak = np.max(np.abs(rir))
    if peak <= 0:
        raise ValueError("silent RIR")
    onset = int(np.argmax(np.abs(rir) >= peak * 10 ** (-40 / 20)))
    start = max(0, onset - GUARD)
    rir = rir[start : start + TAPS]
    if len(rir) < TAPS:
        rir = np.pad(rir, (0, TAPS - len(rir)))
    return rir / np.sqrt(np.sum(rir * rir))


def emit_header(name: str, rir: np.ndarray, provenance: str) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / f"rir_{name}.h"
    lines = [
        "// GENERATED by tools/fixtures/make_rir_fixtures.py — do not edit by hand.",
        "// SPDX-License-Identifier: MIT",
        "// Copyright 2026 MuTap contributors",
        "//",
    ]
    for ln in provenance.splitlines():
        lines.append(f"// {ln}".rstrip())
    lines += [
        # Generated data tables: leave the array layout as emitted here rather
        # than hand it to clang-format (which would re-flow it on every commit).
        "// clang-format off",
        "#pragma once",
        "",
        "namespace mutap_test::fixtures {",
        "",
        f"    inline constexpr unsigned k_rir_{name}_fs   = {FS};",
        f"    inline constexpr unsigned k_rir_{name}_taps = {len(rir)};",
        "",
        f"    inline constexpr float k_rir_{name}[{len(rir)}] = {{",
    ]
    row = []
    for i, v in enumerate(rir):
        row.append(f"{v:.8e}f")
        if len(row) == 4:
            lines.append("        " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("        " + ", ".join(row) + ",")
    lines += ["    };", "", "} // namespace mutap_test::fixtures", ""]
    path.write_text("\n".join(lines))
    print(f"wrote {path} ({len(rir)} taps)")


def generate_modeled(only: str | None = None) -> None:
    import pyroomacoustics as pra

    for name, spec in ROOMS.items():
        if only is not None and name != only:
            continue
        room = pra.ShoeBox(
            spec["dims"],
            fs=FS,
            materials=pra.Material(spec["absorption"]),
            max_order=spec["max_order"],
        )
        room.add_source(spec["speaker"])
        room.add_microphone(spec["mic"])
        room.compute_rir()
        rir = condition(room.rir[0][0])
        provenance = "\n".join(
            [
                f"Physically-modeled room: {spec['blurb']}.",
                f"pyroomacoustics image-source method, shoebox {spec['dims']} m,",
                f"uniform absorption {spec['absorption']}, max_order {spec['max_order']},",
                f"speaker at {spec['speaker']}, mic at {spec['mic']}, fs {FS} Hz.",
                "Deterministic: rebuilding with the same parameters reproduces",
                "this data exactly. Conditioning (delay trim to a 32-sample",
                f"guard, truncation to {TAPS} taps, unit-energy normalization)",
                "is documented in the generator script.",
            ]
        )
        emit_header(name, rir, provenance)


def from_wav(wav_path: str, name: str, source: str) -> None:
    import wave

    with wave.open(wav_path, "rb") as w:
        if w.getnchannels() != 1:
            raise SystemExit("mono WAV required")
        fs = w.getframerate()
        raw = w.readframes(w.getnframes())
        width = w.getsampwidth()
    if width == 2:
        x = np.frombuffer(raw, dtype=np.int16).astype(np.float64) / 32768.0
    elif width == 4:
        x = np.frombuffer(raw, dtype=np.int32).astype(np.float64) / 2147483648.0
    else:
        raise SystemExit(f"unsupported sample width {width}")
    if fs != FS:
        from scipy.signal import resample_poly

        from math import gcd

        g = gcd(FS, fs)
        x = resample_poly(x, FS // g, fs // g)
    provenance = "\n".join(
        [
            f"Measured RIR imported from {pathlib.Path(wav_path).name} (original fs {fs} Hz).",
            f"Source/license: {source}",
            "Conditioning (delay trim to a 32-sample guard, truncation to",
            f"{TAPS} taps, unit-energy normalization) is documented in the",
            "generator script.",
        ]
    )
    emit_header(name, condition(x), provenance)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--generate", action="store_true", help="rebuild the modeled rooms")
    ap.add_argument("--only", default=None, help="with --generate: rebuild a single room "
                    "(committed fixtures are baselines — never regenerate rooms you are not changing)")
    ap.add_argument("--from-wav", nargs=2, metavar=("WAV", "NAME"), help="import a measured RIR")
    ap.add_argument("--source", default="", help="provenance + license text for --from-wav")
    args = ap.parse_args()
    if args.generate:
        generate_modeled(args.only)
    elif args.from_wav:
        if not args.source:
            raise SystemExit("--from-wav requires --source (provenance/license is not optional)")
        from_wav(args.from_wav[0], args.from_wav[1], args.source)
    else:
        ap.print_help()


if __name__ == "__main__":
    main()
